@import Foundation;

#import "JREnum/JREnum.h"

// Mostly stolen from http://abcnews.go.com/blogs/headlines/2014/02/heres-a-list-of-58-gender-options-for-facebook-users/

JREnumDeclare(
              Gender,
              Gender_Undefined,
              Gender_Female,
              Gender_Male,
              Gender_Other,
              Gender_Agender,
              Gender_Androgyne,
              Gender_Androgynous,
              Gender_Bigender,
              Gender_Cisgender,
              Gender_CisgenderFemale,
              Gender_CisgenderMale,
              Gender_FemaleToMale,
              Gender_GenderFluid,
              Gender_GenderNonconforming,
              Gender_GenderQuestioning,
              Gender_GenderVariant,
              Gender_Genderqueer,
              Gender_Intersex,
              Gender_MaleToFemale,
              Gender_Neither,
              Gender_Neutrois,
              Gender_Nonbinary,
              Gender_Pangender,
              Gender_Trans,
              Gender_TransStar,
              Gender_TransFemale,
              Gender_TransStarFemale,
              Gender_TransMale,
              Gender_TransStarMale,
              Gender_TransPerson,
              Gender_TransStarPerson,
              Gender_Transfeminine,
              Gender_Transgender,
              Gender_TransgenderFemale,
              Gender_TransgenderMale,
              Gender_TransgenderPerson,
              Gender_Transmasculine,
              Gender_Transsexual,
              Gender_TranssexualFemale,
              Gender_TranssexualMale,
              Gender_TranssexualPerson,
);
